version: '3.9'

services:
  storage_provider:
    volumes:
      - .:/app:ro
      - /app/node_modules

  website_owner:
    command: 'run start:docker:dev'
    volumes:
      - .:/app:ro
      - /app/node_modules

  website_visitor:
    command: 'run start:docker:dev'
    volumes:
      - .:/app:ro
      - /app/node_modules

  database:
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pointnetwork_pgadmin
    restart: always
    depends_on:
      - database
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pointnetwork.io
      PGADMIN_DEFAULT_PASSWORD: pgadminpass
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
