version: '3.9'

services:
  geth:
    image: ethereum/client-go:v1.9.21
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    volumes:
      - geth_data:/root/.ethereum:rw
      - geth_dagdir:/root/.ethash:rw
      - ${PWD}/raiden.service/keystore:/keystore:ro
      - ${PWD}/raiden.service/geth.genesis.json:/genesis.json:ro
      - ${PWD}/raiden.service/geth.entrypoint.sh:/entrypoint.sh:ro
      - ${PWD}/raiden.service/geth.config.toml:/config.toml:ro
    entrypoint: /entrypoint.sh
    command:
      - --config=/config.toml
      - --networkid
      - '4321'
      - --fakepow
      - --ipcdisable
      - --mine
      - --miner.threads
      - '1'
      - --miner.etherbase
      - '0xE6315BC1e4E12Cb76Dd18258420298E9ad174e67'

  raiden_node_1:
    image: raiden-dev
    depends_on: 
      - geth
    ports:
      - 5011:5001
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - raiden_data:/data:rw
      - raiden_shared:/shared:rw
      # - ${PWD}/debug:/debug:rw
      # - ${PWD}/raiden-contracts-0.37.5/raiden_contracts:/opt/venv/lib/python3.7/site-packages/raiden_contracts:rw
      - ${PWD}/raiden-contracts-0.37.5/raiden_contracts/data:/opt/venv/lib/python3.7/site-packages/raiden_contracts/data_0.37.0:rw
      - ${PWD}/raiden.service/keystore:/keystore:ro
      - ${PWD}/raiden.service/raiden.password.txt:/password.txt:ro
      - ${PWD}/raiden.service/raiden.deployment_private_net.json:/opt/venv/lib/python3.7/site-packages/raiden_contracts/data_0.37.0/deployment_private_net.json:rw
      - ${PWD}/raiden.service/raiden.deployment_private_net.json:/opt/venv/lib/python3.7/site-packages/raiden_contracts/data/deployment_private_net.json:rw
      - ${PWD}/raiden.service/raiden.entrypoint.sh:/entrypoint.sh:ro
    entrypoint:
      - /entrypoint.sh
    command:
      # - --help
      - --no-sync-check
      - --log-config
      - ':DEBUG'
      - --address
      - '0xC01011611e3501C6b3F6dC4B6d3FE644d21aB301'
      - --datadir
      - /data
      - --keystore-path
      - /keystore
      - --password-file
      - /password.txt
      - --network-id
      - '4321'
      - --accept-disclaimer
      - --eth-rpc-endpoint
      - http://geth:8545
      - --rpc
      - --api-address
      - '0.0.0.0:5001'
      - --web-ui
      - --environment-type
      - 'development'
      - --routing-mode
      - 'private'
      - --matrix-server
      - 'http://transport.transport01.raiden.network'
      # # - 'http://matrix:8008'

volumes:
  geth_data:
  geth_dagdir:
  raiden_data:
  raiden_shared:
