version: '3.9'

services:
  storage_provider:
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro

  website_owner:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro
      - ./knexfile.js:/app/knexfile.js:ro

  website_visitor:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro

  database:
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pointnetwork_pgadmin
    restart: always
    depends_on:
      - database
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pointnetwork.io
      PGADMIN_DEFAULT_PASSWORD: pgadminpass
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro