version: '3.9'

services:
  geth:
    image: ethereum/client-go:v1.9.21
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    volumes:
      - geth_data:/root/.ethereum
      - ${PWD}/raiden.service/keystore:/keystore:ro
      - ${PWD}/raiden.service/geth.genesis.json:/genesis.json:ro
      - ${PWD}/raiden.service/geth.entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    command:
      - --keystore
      - /keystore
      - --networkid
      - '4321'
      - --datadir
      - /data
      - --rpc
      - --rpcapi
      - eth,net,web3
      - --rpcaddr
      - '0.0.0.0'
      - --rpcvhosts
      - '*'
      - --rpccorsdomain
      - '*'
      - --mine
      - --miner.threads
      - '1'
      - --miner.etherbase
      - '0xE6315BC1e4E12Cb76Dd18258420298E9ad174e67'

  matrix:
    image: matrixdotorg/synapse:v1.30.0rc1
    ports:
      - "8008:8008"
      - "8448:8448"
      - "3478:3478"
    volumes:
      - ${PWD}/raiden.service/matrix.data:/data:rw

  raiden_node_1:
    image: raidennetwork/raiden:v0.200.0-rc1
    depends_on: 
      - geth
      - matrix
    ports:
      - 5001:5001
    volumes:
      - raiden_data:/data
      - raiden_shared:/shared
      - ${PWD}/raiden.service/keystore:/keystore:ro
      - ${PWD}/raiden.service/raiden.deployment_private_net.json:/opt/venv/lib/python3.7/site-packages/raiden_contracts/data_0.25.0/deployment_private_net.json:rw
      - ${PWD}/raiden.service/raiden.entrypoint.sh:/entrypoint.sh:ro
    entrypoint:
      - /entrypoint.sh
    command:
      - --no-sync-check
      - --address
      - '0xC01011611e3501C6b3F6dC4B6d3FE644d21aB301'
      - --datadir
      - /data
      - --keystore-path
      - /keystore
      - --password-file
      - /pswrd
      - --network-id
      - '4321'
      - --accept-disclaimer
      - --eth-rpc-endpoint
      - http://geth:8545
      - --rpc
      - --api-address
      - '0.0.0.0:5001'
      - --web-ui
      - --environment-type
      - 'development'
      - --routing-mode
      - 'private'
      - --matrix-server
      - 'http://matrix:8008'

volumes:
  geth_data:
  raiden_data:
  raiden_shared:
