version: '3.9'

services:
  geth:
    image: ethereum/client-go:v1.9.21
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    volumes:
      - ./geth_data:/data:rw
      - ./test_keystore:/keystore:ro
      - ./genesis.json:/genesis.json:ro
      - ./geth.init.sh:/init.sh:ro
    entrypoint: /init.sh
    command:
      - --keystore
      - /keystore
      - --networkid
      - '4321'
      - --datadir
      - /data
      - --rpc
      - --rpcapi
      - eth,net,web3
      - --rpcaddr
      - '0.0.0.0'
      - --rpcvhosts
      - '*'
      - --rpccorsdomain
      - '*'
      - --mine
      - --miner.threads
      - '1'
      - --miner.etherbase
      - '0xE6315BC1e4E12Cb76Dd18258420298E9ad174e67'

  raiden_node_1:
    image: raidennetwork/raiden:v0.200.0-rc9
    depends_on:
      - geth
    ports:
      - 5011:5001
    volumes:
      - raiden_data:/data
      - ./test_keystore:/keystore:ro
      - ./test_address_pswrd:/pswrd:ro
      - ./tmp:/tmp:rw
      - ./debug/deployment_private_net.json:/opt/venv/lib/python3.7/site-packages/raiden_contracts/data_0.25.0/deployment_private_net.json:rw
      - ./raiden.docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    entrypoint:
      - '/docker-entrypoint-initdb.d/deploy.contracts.sh'
    command:
      - --help
      # - --address
      # - '0xC01011611e3501C6b3F6dC4B6d3FE644d21aB301'
      # - --datadir
      # - /data
      # - --keystore-path
      # - /keystore
      # - --password-file
      # - /pswrd
      # - --network-id
      # - '4321'
      # - --accept-disclaimer
      # - --eth-rpc-endpoint
      # - http://geth:8545
      # - --rpc
      # - --api-address
      # - '0.0.0.0:5001'
      # - --web-ui
      # - --environment-type
      # - 'development'
      # - --routing-mode
      # - 'private'

volumes:
  raiden_data:
